### ISSUE TITLE
Android app crashes due to the exception: java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by xzdev** [alwx/react-native-photo-view#15]
Does anyone has the crash problem on Android. Here is my error log:
```
E/InputEventReceiver(25713): Exception dispatching input event.
E/MtaSDK  (25713): 
E/MtaSDK  (25713): java.lang.IllegalArgumentException: pointerIndex out of range pointerIndex=-1 pointerCount=1
E/MtaSDK  (25713): 	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
E/MtaSDK  (25713): 	at android.view.MotionEvent.getX(MotionEvent.java:2023)
E/MtaSDK  (25713): 	at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
E/MtaSDK  (25713): 	at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:110)
E/MtaSDK  (25713): 	at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:462)
E/MtaSDK  (25713): 	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1987)
E/MtaSDK  (25713): 	at com.facebook.react.views.viewpager.ReactViewPager.onInterceptTouchEvent(ReactViewPager.java:149)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1951)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
E/MtaSDK  (25713): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
E/MtaSDK  (25713): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2345)
E/MtaSDK  (25713): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1708)
E/MtaSDK  (25713): 	at android.app.Dialog.dispatchTouchEvent(Dialog.java:807)
E/MtaSDK  (25713): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2306)
E/MtaSDK  (25713): 	at android.view.View.dispatchPointerEvent(View.java:8483)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4291)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4157)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3662)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3715)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3681)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3689)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3662)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3715)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3681)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3689)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3662)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5978)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5952)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5923)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6081)
E/MtaSDK  (25713): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
E/MtaSDK  (25713): 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
E/MtaSDK  (25713): 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6039)
E/MtaSDK  (25713): 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6148)
E/MtaSDK  (25713): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793)
E/MtaSDK  (25713): 	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
E/MtaSDK  (25713): 	at android.vi
E/AndroidRuntime(25713): FATAL EXCEPTION: main
E/AndroidRun
```
This could be the same [Android ViewPager issue](https://github.com/chrisbanes/PhotoView/issues/31). The proposed way is to override onInterceptTouchEvent to catch the exception.

**Comment by vandervidi** [comment]
@xzdev I get the same crash :(
Did you fix this?

**Comment by alwx** [comment]
@xzdev @vandervidi need to see your code to understand the problem.

**Comment by waleedarshad-vf** [comment]
Same problem +1

**Comment by waleedarshad-vf** [comment]
on zooming in and out it just crashed randomly :(

**Comment by zsajjad** [comment]
Same issue on zooming out to maximum!

**Comment by juanmanuelarze** [comment]
same here

**Comment by edencakir** [comment]
same

**Comment by loiclouvet** [comment]
Same issue

**Comment by GuillaumeMunsch** [comment]
Same here

**Comment by Borisboky** [comment]
+1

**Comment by douglasjunior** [comment]
Same here, only for two Samsung devices.

**Comment by JonoH** [comment]
+1

**Comment by JiboStore** [comment]
me too, any solution?

I found this:
https://github.com/chrisbanes/PhotoView/issues/293

But I'm not sure how to apply, pretty new to react-native here...

**Comment by carstenhag** [comment]
See https://issuetracker.google.com/issues/143448308, they won't fix it. ViewPager (1) is now also deprecated so move to ViewPager2.
