### ISSUE TITLE
[Android] crash on component render

### ISSUE THREAD

**Issue by stereodenis** [alwx/react-native-photo-view#18]
```
09-04 00:59:07.843 15575-15575/com.evrone.pshpsh E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.evrone.pshpsh, PID: 15575
                                                                   java.lang.NoSuchMethodError: com.facebook.react.uimanager.events.Event.<init>
                                                                       at com.reactnative.photoview.ImageEvent.<init>(ImageEvent.java:37)
                                                                       at com.reactnative.photoview.PhotoView$1.onSubmit(PhotoView.java:93)
                                                                       at com.facebook.drawee.controller.AbstractDraweeController.submitRequest(AbstractDraweeController.java:395)
                                                                       at com.facebook.drawee.controller.AbstractDraweeController.onAttach(AbstractDraweeController.java:339)
                                                                       at com.facebook.drawee.view.DraweeHolder.attachController(DraweeHolder.java:297)
                                                                       at com.facebook.drawee.view.DraweeHolder.attachOrDetachController(DraweeHolder.java:314)
                                                                       at com.facebook.drawee.view.DraweeHolder.onAttach(DraweeHolder.java:121)
                                                                       at com.facebook.drawee.view.DraweeView.doAttach(DraweeView.java:165)
                                                                       at com.facebook.drawee.view.DraweeView.onAttach(DraweeView.java:151)
                                                                       at com.facebook.drawee.view.DraweeView.onAttachedToWindow(DraweeView.java:128)
                                                                       at me.relex.photodraweeview.PhotoDraweeView.onAttachedToWindow(PhotoDraweeView.java:56)
                                                                       at android.view.View.dispatchAttachedToWindow(View.java:12851)
                                                                       at android.view.ViewGroup.addViewInner(ViewGroup.java:3759)
                                                                       at android.view.ViewGroup.addView(ViewGroup.java:3566)
                                                                       at android.view.ViewGroup.addView(ViewGroup.java:3511)
                                                                       at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:196)
                                                                       at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:39)
                                                                       at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:387)
                                                                       at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:175)
                                                                       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:782)
                                                                       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
                                                                       at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
                                                                       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:868)
                                                                       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
                                                                       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:619)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:587)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:802)
                                                                       at android.os.Handler.handleCallback(Handler.java:808)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                       at android.os.Looper.loop(Looper.java:193)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5388)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655)
                                                                       at dalvik.system.NativeStart.main(Native Method)
```

**Comment by tomershohet** [comment]
+1

**Comment by Rpaixao** [comment]
+1

**Comment by marcshilling** [comment]
It renders fine for me, but I get the same crash immediately upon trying to pinch to zoom.
