### ISSUE TITLE
Image pinch error.

### ISSUE THREAD

**Issue by susylPearl** [alwx/react-native-photo-view#5]
when i pinch in , app gets crasched in android studio monitor error shows as:
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                             at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1014)
                                                                             at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1282)
                                                                             at com.facebook.react.views.drawer.ReactDrawerLayout.onInterceptTouchEvent(ReactDrawerLayout.java:37)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at a

**Comment by avishayil** [comment]
Same here

**Comment by alwx** [comment]
@susylPearl Which ViewPager do you use? I think it is ViewPager-related issue. Please, post your code to let me check.

**Comment by susylPearl** [comment]
https://gist.github.com/susylPearl/1ea70bcdff41e3f4bfaf0fca20ea2ecd i have used this view pager.

**Comment by alwx** [comment]
@susylPearl This is definitely ViewPager-related problem. Does it work if you replace PhotoView with any other component (ImageView, for instance)?


Btw, the recommended aproach is to use ScrollView instead of custom pager. ScrollView supports paging and works perfectly on both Android and iOS.

**Comment by susylPearl** [comment]
Could you please provide me a example?? I will be very thankful.

**Comment by alwx** [comment]
I've added an example to repository. Thanks for your patience!
