### ISSUE TITLE
[Android] pinching to zoom out crash application

### ISSUE THREAD

**Issue by valinaga** [alwx/react-native-photo-view#83]
If you pinch the screen to zoom out beyond a certain size, the app crash with this exception:

`java.lang.IllegalArgumentException: pointerIndex out of range
 	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
 	at android.view.MotionEvent.getX(MotionEvent.java:2072)
 	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2092)
 	at com.facebook.react.views.viewpager.ReactViewPager.onInterceptTouchEvent(ReactViewPager.java:181)
 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)`

**Comment by OisinOKeeffe** [comment]
Having the same issue. Hoping we can get this and #69 for android soon.

**Comment by VinceBT** [comment]
Would be nice to have

**Comment by Borisboky** [comment]
+1

**Comment by Jagadeesh-Govindaraj** [comment]
any update on this

**Comment by VinceBT** [comment]
+1

**Comment by tiberiumihai** [comment]
+1

**Comment by JonoH** [comment]
+1

**Comment by saintego** [comment]
+1

**Comment by JonathanAJ** [comment]
+1

**Comment by JonathanAJ** [comment]
Any solution?

**Comment by kapil-kumawat** [comment]
Having the same issue. any update?

**Comment by AshbaLee** [comment]
@kapil-kumawat @JonathanAJ 
I fix this problem by including another package [react-native-image-zoom](https://github.com/AshbaLee/react-native-image-zoom)

Here is code:
```
import PhotoView from 'react-native-photo-view';
import { ViewPagerZoom } from 'react-native-image-zoom';
...
<ViewPagerZoom style={{ width: Dimensions.get('window').width, height: Dimensions.get('window').height-200}}>
    <View>
    <PhotoView
        source={{
            uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png'
        }}
        androidScaleType={"fitCenter"}
        style={{ width: Dimensions.get('window').width, height: Dimensions.get('window').height-200 }}
    />
    </View>
</ViewPagerZoom>
...
```
